// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUeaFusgeiRb43jGOoX_cWTvF7P4zJNWA',
    appId: '1:41486168204:web:4ab8162623b3bce55d4ba9',
    messagingSenderId: '41486168204',
    projectId: 'chat-25ba6',
    authDomain: 'chat-25ba6.firebaseapp.com',
    storageBucket: 'chat-25ba6.appspot.com',
    measurementId: 'G-3TCLZ86S2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4zepdodlky1Gd58aPlSCwkeAdpsMKLUE',
    appId: '1:41486168204:android:50ba893d6afc688a5d4ba9',
    messagingSenderId: '41486168204',
    projectId: 'chat-25ba6',
    storageBucket: 'chat-25ba6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuMRy3rCeWnPoyHDrBYrQVUeNPCJjfix4',
    appId: '1:41486168204:ios:86beab46a67c86f25d4ba9',
    messagingSenderId: '41486168204',
    projectId: 'chat-25ba6',
    storageBucket: 'chat-25ba6.appspot.com',
    iosClientId: '41486168204-nvr865h2g7o6es2m86t15g9evfo7j358.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuMRy3rCeWnPoyHDrBYrQVUeNPCJjfix4',
    appId: '1:41486168204:ios:86beab46a67c86f25d4ba9',
    messagingSenderId: '41486168204',
    projectId: 'chat-25ba6',
    storageBucket: 'chat-25ba6.appspot.com',
    iosClientId: '41486168204-nvr865h2g7o6es2m86t15g9evfo7j358.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
